# Generated by Django 5.0 on 2025-11-27 20:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mixpanel_enabled', models.BooleanField(default=False)),
                ('mixpanel_token', models.CharField(blank=True, max_length=100)),
                ('mixpanel_api_secret', models.CharField(blank=True, max_length=100)),
                ('ga_enabled', models.BooleanField(default=False)),
                ('ga_measurement_id', models.CharField(blank=True, max_length=50)),
                ('ga_api_secret', models.CharField(blank=True, max_length=100)),
                ('webhook_enabled', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=100)),
                ('internal_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('conversion_window_hours', models.PositiveIntegerField(default=168)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('distinct_id', models.CharField(db_index=True, max_length=200)),
                ('anonymous_id', models.CharField(blank=True, max_length=200)),
                ('user_id', models.CharField(blank=True, max_length=200)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='web', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forwarded_to_mixpanel', models.BooleanField(default=False)),
                ('forwarded_to_ga', models.BooleanField(default=False)),
                ('forwarded_to_webhook', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'event_name', 'timestamp'], name='analytics_e_tenant__e61111_idx'), models.Index(fields=['tenant', 'distinct_id', 'timestamp'], name='analytics_e_tenant__01e5e6_idx'), models.Index(fields=['tenant', 'timestamp'], name='analytics_e_tenant__49488d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunnelConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distinct_id', models.CharField(max_length=200)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='analytics.funnel')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['funnel', 'distinct_id'], name='analytics_f_funnel__05250b_idx'), models.Index(fields=['funnel', 'is_completed'], name='analytics_f_funnel__e137d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=100)),
                ('property_filters', models.JSONField(blank=True, default=dict)),
                ('funnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='analytics.funnel')),
            ],
            options={
                'ordering': ['funnel', 'order'],
                'unique_together': {('funnel', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distinct_id', models.CharField(max_length=200)),
                ('properties', models.JSONField(default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_users', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'distinct_id'], name='analytics_u_tenant__76ee25_idx'), models.Index(fields=['tenant', 'last_seen'], name='analytics_u_tenant__12be62_idx')],
                'unique_together': {('tenant', 'distinct_id')},
            },
        ),
    ]
