# Generated by Django 5.0 on 2025-12-13 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_type', models.CharField(blank=True, max_length=100)),
                ('user_needs', models.TextField(blank=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('total_builds', models.IntegerField(default=0)),
                ('successful_builds', models.IntegerField(default=0)),
                ('total_modifications', models.IntegerField(default=0)),
                ('journey_summary', models.TextField(blank=True)),
                ('satisfaction_score', models.FloatField(blank=True, null=True)),
                ('all_messages', models.JSONField(default=list)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('task_type', models.CharField(db_index=True, max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_token', 'created_at'], name='analytics_a_session_6566f1_idx'), models.Index(fields=['user_id', 'created_at'], name='analytics_a_user_id_d3e7fe_idx'), models.Index(fields=['model', 'created_at'], name='analytics_a_model_b9762a_idx'), models.Index(fields=['task_type', 'created_at'], name='analytics_a_task_ty_a8fe6a_idx'), models.Index(fields=['created_at'], name='analytics_a_created_20fcf5_idx')],
            },
        ),
    ]
