# Generated by Django 5.0 on 2025-12-18 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_adminconfig_aiinsight_alertrule_buildqueueitem_and_more'),
        ('code_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentgapanalysis',
            name='addressed_by_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_library.libraryitem'),
        ),
        migrations.AddIndex(
            model_name='customerhealthscore',
            index=models.Index(fields=['health_status', 'overall_score'], name='analytics_c_health__ab575e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerhealthscore',
            index=models.Index(fields=['session_token'], name='analytics_c_session_c3667a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerhealthscore',
            index=models.Index(fields=['email'], name='analytics_c_email_5ccc47_idx'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='scheduled_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.scheduledreport'),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['metric_type', '-recorded_at'], name='analytics_s_metric__5639ff_idx'),
        ),
    ]
