# Generated by Django 5.0 on 2025-11-20 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='projects.project'),
        ),
        migrations.AddField(
            model_name='generatedapi',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedmodel',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='generatedapi',
            unique_together={('project', 'path', 'method')},
        ),
        migrations.AlterUniqueTogether(
            name='projectversion',
            unique_together={('project', 'version')},
        ),
    ]
