# Generated by Django 5.0 on 2025-12-28 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_unique_together_project_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('openweather', 'OpenWeather'), ('alpha_vantage', 'Alpha Vantage (Stocks)'), ('finnhub', 'Finnhub (Stocks)'), ('newsapi', 'News API'), ('stripe', 'Stripe'), ('shopify', 'Shopify'), ('custom', 'Custom API')], max_length=50)),
                ('service_name', models.CharField(blank=True, help_text='Display name', max_length=100)),
                ('api_key', models.CharField(max_length=500)),
                ('base_url', models.URLField(blank=True, help_text='For custom APIs')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('invalid', 'Invalid'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('call_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='projects.project')),
            ],
            options={
                'verbose_name': 'Customer API Key',
                'verbose_name_plural': 'Customer API Keys',
                'unique_together': {('project', 'service')},
            },
        ),
    ]
