# Generated by Django 5.0 on 2026-01-15 20:29

from django.db import migrations, models


def add_preferred_model_if_not_exists(apps, schema_editor):
    """Add preferred_model column only if it doesn't exist (idempotent)."""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name FROM information_schema.columns
            WHERE table_name = 'projects_project' AND column_name = 'preferred_model'
        """)
        if cursor.fetchone() is None:
            cursor.execute("""
                ALTER TABLE projects_project
                ADD COLUMN preferred_model VARCHAR(50) DEFAULT 'claude-opus'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_customer_api_keys'),
    ]

    operations = [
        migrations.RunPython(add_preferred_model_if_not_exists, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
