# Generated by Django 5.0 on 2026-01-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_customer_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preferred_model',
            field=models.CharField(choices=[('claude-opus', 'Claude Opus 4.5 - Most Powerful'), ('claude-sonnet', 'Claude Sonnet 4 - Balanced'), ('claude-haiku', 'Claude Haiku 3.5 - Fast')], default='claude-opus', help_text='AI model to use for code generation', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
