# Generated by Django 5.0 on 2026-02-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_fix_preferred_model_sqlite'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pending_modification',
            field=models.TextField(blank=True, help_text='Pending modification request awaiting user confirmation', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('building', 'Building'), ('ready', 'Ready'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
    ]
