"""
V3 Generator - Universal App Builder

Now with COMPONENT-BASED generation:
1. Decompose request into building blocks
2. Search library for each block
3. Reuse found blocks, generate missing ones
4. Save new blocks to library
5. Compose final app
"""
import json
import logging
from typing import Dict, Any, Optional

from ..ai_client import AIClient
from .prompts import get_prompt_for_request, get_modify_prompt, get_analyze_prompt

# Component-based generation
from apps.code_library.component_pipeline import ComponentGenerationPipeline

logger = logging.getLogger(__name__)


# Feature flag - set to True to use component-based generation
USE_COMPONENT_PIPELINE = True


class UniversalGenerator:
    """
    V3 Generator that creates apps using the Universal Gateway
    """
    
    def __init__(self):
        self.client = AIClient()
    
    def analyze_request(self, user_prompt: str) -> Dict[str, Any]:
        """Analyze user request to understand what they want"""
        try:
            prompt = get_analyze_prompt(user_prompt)
            messages = [
                {"role": "system", "content": "You are an expert at understanding user requirements. Respond with JSON only."},
                {"role": "user", "content": prompt}
            ]
            response = self.client.chat_completion(messages)
            return json.loads(response)
        except Exception as e:
            logger.error(f"Analysis failed: {e}")
            return {
                'app_type': 'website',
                'complexity': 'medium',
                'needs_backend': False,
                'external_apis': [],
                'suggested_services': ['coingecko', 'yahoo_finance']
            }
    
    def generate(self, user_prompt: str, project_id: int = None, max_retries: int = 2) -> Dict[str, Any]:
        """
        Generate a complete app from user prompt.
        
        NEW: Uses component-based generation:
        1. Decompose into building blocks
        2. Search library for each block
        3. Reuse found, generate missing
        4. Save new blocks to library
        5. Compose final app
        
        Returns:
            {
                'app_type': str,
                'title': str,
                'components': {'App': '...code...'},
                'api_services': [...],
                'build_stats': {...}  # NEW: component reuse stats
            }
        """
        logger.info(f"[{project_id}] Generating app for: {user_prompt[:100]}...")
        
        # NEW: Use component pipeline if enabled
        if USE_COMPONENT_PIPELINE:
            return self._generate_with_components(user_prompt, project_id)
        
        # LEGACY: Fallback to monolithic generation
        return self._generate_legacy(user_prompt, project_id, max_retries)
    
    def _generate_with_components(self, user_prompt: str, project_id: int = None) -> Dict[str, Any]:
        """
        NEW: Component-based generation.
        
        Each project is decomposed into building blocks (navigation, hero, 
        footer, cards, tables, charts, etc.). Each block is either:
        - Reused from library (if a matching block exists)
        - Generated by Opus 4.5 and saved to library
        
        This enables TRUE reuse - not whole projects, but individual components.
        """
        print(f"[GENERATOR] Using COMPONENT-BASED generation for project {project_id}")
        
        try:
            pipeline = ComponentGenerationPipeline(session=None)
            
            # Build using component blocks
            code = pipeline.build(user_prompt, project=None)
            
            # Get stats
            stats = pipeline.get_stats()
            
            print(f"[GENERATOR] Component build complete:")
            print(f"  Required: {stats['components_required']}")
            print(f"  Reused: {stats['components_reused']}")
            print(f"  Generated: {stats['components_generated']}")
            
            # Build result
            return {
                'app_type': self._detect_app_type(user_prompt),
                'title': self._generate_title(user_prompt),
                'components': {'App': code},
                'api_services': self._detect_services(code),
                'build_stats': stats  # Include reuse stats
            }
            
        except Exception as e:
            logger.error(f"[{project_id}] Component generation failed: {e}")
            print(f"[GENERATOR] Component generation failed, falling back to legacy: {e}")
            return self._generate_legacy(user_prompt, project_id, max_retries=2)
    
    def _detect_app_type(self, prompt: str) -> str:
        """Detect app type from prompt."""
        prompt_lower = prompt.lower()
        if 'dashboard' in prompt_lower:
            return 'dashboard'
        elif 'landing' in prompt_lower:
            return 'landing'
        elif 'portfolio' in prompt_lower:
            return 'portfolio'
        elif 'ecommerce' in prompt_lower or 'shop' in prompt_lower:
            return 'ecommerce'
        elif 'form' in prompt_lower:
            return 'form'
        return 'website'
    
    def _generate_title(self, prompt: str) -> str:
        """Generate a title from prompt."""
        words = prompt.split()[:5]
        return ' '.join(words).title()
    
    def _detect_services(self, code: str) -> list:
        """Detect API services used in code."""
        services = []
        if 'yahoo_finance' in code:
            services.append('yahoo_finance')
        if 'coingecko' in code:
            services.append('coingecko')
        if 'restcountries' in code:
            services.append('restcountries')
        return services
    
    def _generate_legacy(self, user_prompt: str, project_id: int = None, max_retries: int = 2) -> Dict[str, Any]:
        """Legacy monolithic generation (fallback)."""
        last_error = None
        
        for attempt in range(max_retries + 1):
            try:
                # Get prompt with relevant hints
                prompt = get_prompt_for_request(user_prompt)
                
                # On retry, add instruction to be more concise
                if attempt > 0:
                    logger.info(f"[{project_id}] Retry attempt {attempt}...")
                    prompt += "\n\nIMPORTANT: Keep the code concise. Focus on core functionality."
                
                # Generate
                messages = [
                    {"role": "system", "content": "You are an expert React developer. Return ONLY valid JSON with complete code."},
                    {"role": "user", "content": prompt}
                ]
                response = self.client.chat_completion(messages)
                
                # Parse response
                result = self._parse_generation_response(response, project_id)
                
                if result:
                    logger.info(f"[{project_id}] Generated {result.get('app_type', 'unknown')} app")
                    return result
                    
            except Exception as e:
                last_error = e
                error_str = str(e)
                logger.warning(f"[{project_id}] Attempt {attempt + 1} failed: {e}")
                
                # Handle rate limits with exponential backoff
                if 'rate_limit' in error_str or '429' in error_str:
                    import time
                    wait_time = 30 * (attempt + 1)  # 30s, 60s, 90s
                    logger.info(f"[{project_id}] Rate limited. Waiting {wait_time}s...")
                    time.sleep(wait_time)
                
                if attempt < max_retries:
                    continue
        
        # All retries failed
        logger.error(f"[{project_id}] All generation attempts failed: {last_error}")
        raise ValueError(f"Generation failed after {max_retries + 1} attempts: {last_error}")
    
    def _parse_generation_response(self, response: str, project_id: int = None) -> Optional[Dict[str, Any]]:
        """Parse and validate generation response"""
        try:
            # Clean response
            response = response.strip()
            if response.startswith('```'):
                response = response.split('\n', 1)[1]
                response = response.rsplit('```', 1)[0]
            
            result = json.loads(response)
            
            # Validate required fields
            if 'components' not in result or 'App' not in result.get('components', {}):
                raise ValueError("Missing App component")
            
            # Ensure code is complete
            app_code = result['components']['App']
            
            # Check for truncation
            if self._is_truncated(app_code):
                app_code = self._complete_truncated_code(app_code)
                result['components']['App'] = app_code
            
            # Ensure imports are present
            if 'import React' not in app_code:
                imports = self._detect_needed_imports(app_code)
                app_code = imports + '\n\n' + app_code
                result['components']['App'] = app_code
            
            # Ensure export
            if 'export default' not in app_code:
                app_code += '\n\nexport default App;'
                result['components']['App'] = app_code
            
            return result
            
        except json.JSONDecodeError as e:
            logger.error(f"[{project_id}] JSON parse error: {e}")
            logger.error(f"Response was: {response[:500]}")
            
            # Try to extract code anyway
            if 'function App' in response or 'const App' in response:
                return self._extract_code_from_response(response)
            
            raise ValueError(f"Invalid JSON response: {e}")
    
    def _is_truncated(self, code: str) -> bool:
        """Check if code appears to be truncated"""
        code = code.strip()
        
        # Check for common truncation signs
        if not code:
            return True
        
        # Count brackets
        open_braces = code.count('{') 
        close_braces = code.count('}')
        open_parens = code.count('(')
        close_parens = code.count(')')
        
        # If significantly unbalanced, probably truncated
        if open_braces - close_braces > 2:
            return True
        if open_parens - close_parens > 2:
            return True
        
        # Check if ends with export
        if 'export default' not in code:
            return True
        
        return False
    
    def _complete_truncated_code(self, code: str) -> str:
        """Attempt to complete truncated code"""
        code = code.strip()
        
        # Balance braces
        open_braces = code.count('{')
        close_braces = code.count('}')
        missing_braces = open_braces - close_braces
        
        if missing_braces > 0:
            # Add closing for JSX, function, and component
            code += '\n' + '  );' * min(missing_braces // 2, 3)  # Close JSX
            code += '\n' + '}' * max(0, missing_braces - (min(missing_braces // 2, 3) * 2))
        
        # Ensure export
        if 'export default' not in code:
            code += '\n\nexport default App;'
        
        return code
    
    def modify(self, current_code: str, user_request: str, project_id: int = None) -> str:
        """
        Modify existing app based on user request
        
        Returns: Modified code string
        """
        logger.info(f"[{project_id}] Modifying app: {user_request[:100]}...")
        
        prompt = get_modify_prompt(current_code, user_request)
        
        messages = [
            {"role": "system", "content": "You are an expert React developer. Return ONLY code."},
            {"role": "user", "content": prompt}
        ]
        response = self.client.chat_completion(messages)
        
        # Clean response
        code = response.strip()
        if code.startswith('```'):
            code = code.split('\n', 1)[1]
            code = code.rsplit('```', 1)[0]
        
        # Ensure imports
        if 'import React' not in code:
            imports = self._detect_needed_imports(code)
            code = imports + '\n\n' + code
        
        # Ensure export
        if 'export default' not in code:
            code += '\n\nexport default App;'
        
        return code
    
    def _detect_needed_imports(self, code: str) -> str:
        """Detect and generate needed React imports"""
        hooks = []
        if 'useState' in code:
            hooks.append('useState')
        if 'useEffect' in code:
            hooks.append('useEffect')
        if 'useRef' in code:
            hooks.append('useRef')
        if 'useCallback' in code:
            hooks.append('useCallback')
        if 'useMemo' in code:
            hooks.append('useMemo')
        
        if hooks:
            return f"import React, {{ {', '.join(hooks)} }} from 'react';"
        return "import React from 'react';"
    
    def _extract_code_from_response(self, response: str) -> Dict[str, Any]:
        """Extract code from non-JSON response"""
        # Find the code block
        if '```' in response:
            parts = response.split('```')
            for part in parts:
                if 'function App' in part or 'const App' in part:
                    code = part.strip()
                    if code.startswith('jsx') or code.startswith('javascript') or code.startswith('tsx'):
                        code = code.split('\n', 1)[1]
                    break
            else:
                code = response
        else:
            code = response
        
        # Ensure imports
        if 'import React' not in code:
            imports = self._detect_needed_imports(code)
            code = imports + '\n\n' + code
        
        if 'export default' not in code:
            code += '\n\nexport default App;'
        
        return {
            'app_type': 'website',
            'title': 'Generated App',
            'components': {'App': code},
            'api_services': []
        }

