# Generated by Django 5.0 on 2025-11-27 22:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('churned_users', models.IntegerField(default=0)),
                ('total_tenants', models.IntegerField(default=0)),
                ('new_tenants', models.IntegerField(default=0)),
                ('active_tenants', models.IntegerField(default=0)),
                ('free_tier_count', models.IntegerField(default=0)),
                ('starter_tier_count', models.IntegerField(default=0)),
                ('pro_tier_count', models.IntegerField(default=0)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, help_text='Monthly Recurring Revenue', max_digits=12)),
                ('arr', models.DecimalField(decimal_places=2, default=0, help_text='Annual Recurring Revenue', max_digits=12)),
                ('total_llm_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_credits_consumed', models.IntegerField(default=0)),
                ('total_llm_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_projects', models.IntegerField(default=0)),
                ('new_projects', models.IntegerField(default=0)),
                ('deployed_projects', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_requests_1h', models.IntegerField(default=0)),
                ('api_errors_1h', models.IntegerField(default=0)),
                ('api_avg_response_ms', models.IntegerField(default=0)),
                ('db_connections', models.IntegerField(default=0)),
                ('db_query_avg_ms', models.IntegerField(default=0)),
                ('queue_pending', models.IntegerField(default=0)),
                ('queue_failed', models.IntegerField(default=0)),
                ('storage_used_gb', models.FloatField(default=0)),
                ('storage_limit_gb', models.FloatField(default=0)),
                ('llm_requests_1h', models.IntegerField(default=0)),
                ('llm_errors_1h', models.IntegerField(default=0)),
                ('llm_avg_response_ms', models.IntegerField(default=0)),
                ('overall_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'System Health',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('google_ads', 'Google Ads'), ('facebook', 'Facebook/Meta'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X')], default='google_ads', max_length=20)),
                ('external_campaign_id', models.CharField(blank=True, max_length=100)),
                ('external_ad_account_id', models.CharField(blank=True, max_length=100)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('target_url', models.URLField(blank=True)),
                ('target_keywords', models.JSONField(blank=True, default=list)),
                ('target_audiences', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_conversions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0, help_text='Click-through rate')),
                ('cpc', models.DecimalField(decimal_places=2, default=0, help_text='Cost per click', max_digits=6)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, help_text='Cost per acquisition', max_digits=8)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunnelConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funnel_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('step_counts', models.JSONField(default=dict, help_text='Step name to count')),
                ('step_to_step_rates', models.JSONField(default=dict, help_text='Step to next step conversion rates')),
                ('total_started', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('overall_conversion_rate', models.FloatField(default=0)),
                ('by_source', models.JSONField(blank=True, default=dict)),
                ('by_campaign', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('funnel_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funnel_name', models.CharField(max_length=100)),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['funnel_name', 'step_order'],
                'unique_together': {('funnel_name', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='AdCampaignDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='platform_admin.adcampaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('funnel_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_admin.funnelstep')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['funnel_step', 'timestamp'], name='platform_ad_funnel__13f9d8_idx'), models.Index(fields=['utm_source', 'utm_campaign'], name='platform_ad_utm_sou_5f4c54_idx')],
            },
        ),
    ]
