# Generated by Django 5.0 on 2025-11-27 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_unique_together_project_tenant_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pattern_type', models.CharField(choices=[('common_request', 'Common Request Type'), ('common_error', 'Common Error'), ('common_complaint', 'Common Complaint'), ('feature_gap', 'Feature Gap'), ('framework_trend', 'Framework/Tech Trend'), ('quality_issue', 'Quality Issue Pattern')], max_length=30)),
                ('keywords', models.JSONField(default=list)),
                ('example_inputs', models.JSONField(default=list)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('action_taken', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('first_detected_at', models.DateTimeField()),
                ('last_detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurrence_count'],
            },
        ),
        migrations.CreateModel(
            name='CustomerHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.IntegerField(default=100, help_text='0-100 health score')),
                ('satisfaction_score', models.IntegerField(default=100)),
                ('engagement_score', models.IntegerField(default=100)),
                ('success_rate', models.FloatField(default=1.0)),
                ('is_at_risk', models.BooleanField(default=False)),
                ('risk_reasons', models.JSONField(default=list)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('total_inputs', models.IntegerField(default=0)),
                ('total_accepted', models.IntegerField(default=0)),
                ('total_rejected', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('unresolved_issues', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_score', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'Customer Health Scores',
                'ordering': ['health_score'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('code_generation', 'Code Generation'), ('code_modification', 'Code Modification'), ('code_fix', 'Code Fix/Debug'), ('code_explanation', 'Code Explanation'), ('chat', 'AI Chat'), ('project_creation', 'Project Creation'), ('feature_request', 'Feature Request'), ('other', 'Other')], max_length=30)),
                ('user_input', models.TextField(help_text='What the customer asked for')),
                ('context', models.TextField(blank=True, help_text='Additional context provided')),
                ('llm_response', models.TextField(help_text='What Faibric returned')),
                ('model_used', models.CharField(max_length=50)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending Review'), ('good', 'Good Quality'), ('needs_review', 'Needs Review'), ('flagged', 'Flagged for Improvement'), ('fixed', 'Fixed by Admin')], default='pending', max_length=20)),
                ('was_error', models.BooleanField(default=False)),
                ('response_too_short', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 rating from user', null=True)),
                ('user_accepted', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_inputs', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminFix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('improved_response', models.TextField(help_text="Admin's improved response")),
                ('fix_notes', models.TextField(blank=True, help_text='Notes about what was fixed')),
                ('fix_method', models.CharField(choices=[('manual', 'Manual Edit'), ('regenerated', 'Regenerated with Claude Opus 4.5'), ('hybrid', 'AI + Manual Edit')], max_length=20)),
                ('improved_prompt', models.TextField(blank=True, help_text='Improved prompt used for regeneration')),
                ('customer_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification_email_id', models.CharField(blank=True, max_length=100)),
                ('customer_viewed', models.BooleanField(default=False)),
                ('customer_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_accepted_fix', models.BooleanField(blank=True, null=True)),
                ('customer_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_fixes', to=settings.AUTH_USER_MODEL)),
                ('customer_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fixes', to='insights.customerinput')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_inputs', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('total_tenants', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('needs_review_count', models.IntegerField(default=0)),
                ('fixed_count', models.IntegerField(default=0)),
                ('by_input_type', models.JSONField(default=dict)),
                ('by_quality_status', models.JSONField(default=dict)),
                ('by_model', models.JSONField(default=dict)),
                ('top_issues', models.JSONField(default=list)),
                ('top_patterns', models.JSONField(default=list)),
                ('customers_needing_attention', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('report_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('approved', 'Approved - Quality OK'), ('needs_fix', 'Needs Fix'), ('fixed', 'Fixed'), ('wont_fix', "Won't Fix"), ('learning', 'Added to Learning')], max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('quality_score', models.IntegerField(blank=True, help_text='1-10 quality assessment', null=True)),
                ('issue_category', models.CharField(blank=True, choices=[('incorrect_code', 'Incorrect Code'), ('incomplete', 'Incomplete Response'), ('wrong_language', 'Wrong Language/Framework'), ('poor_quality', 'Poor Code Quality'), ('misunderstood', 'Misunderstood Request'), ('hallucination', 'Hallucination'), ('outdated', 'Outdated Approach'), ('security', 'Security Issue'), ('other', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='insights.customerinput')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerinput',
            index=models.Index(fields=['tenant', 'created_at'], name='insights_cu_tenant__f0f90f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinput',
            index=models.Index(fields=['user', 'created_at'], name='insights_cu_user_id_ea69db_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinput',
            index=models.Index(fields=['quality_status', 'created_at'], name='insights_cu_quality_fc4a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinput',
            index=models.Index(fields=['input_type', 'created_at'], name='insights_cu_input_t_ae609b_idx'),
        ),
    ]
