# Generated by Django 5.0 on 2025-11-27 21:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('variants', models.JSONField(default=list, help_text='List of variant configs with model/strategy/weight')),
                ('traffic_percentage', models.IntegerField(default=100, help_text='Percentage of requests to include in experiment')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('winning_variant', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_experiments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text="External ID from customer's system", max_length=255)),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('article', 'Article'), ('video', 'Video'), ('course', 'Course'), ('service', 'Service'), ('custom', 'Custom')], default='product', max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('subcategory', models.CharField(blank=True, max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Item attributes like color, size, genre, tags, etc.')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('image_url', models.URLField(blank=True)),
                ('url', models.URLField(blank=True, help_text='Link to item page')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('rating_sum', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-purchase_count', '-view_count'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based'), ('hybrid', 'Hybrid'), ('popularity', 'Popularity-Based'), ('trending', 'Trending')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_events_count', models.IntegerField(default=0)),
                ('training_users_count', models.IntegerField(default=0)),
                ('training_items_count', models.IntegerField(default=0)),
                ('model_data', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('ready', 'Ready'), ('failed', 'Failed'), ('deprecated', 'Deprecated')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_models', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(max_length=255)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('favorite_categories', models.JSONField(blank=True, default=list)),
                ('disliked_items', models.JSONField(blank=True, default=list)),
                ('user_embedding', models.JSONField(blank=True, null=True)),
                ('total_views', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_users', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase'), ('rating', 'Rating'), ('review', 'Review'), ('share', 'Share'), ('favorite', 'Favorite'), ('search', 'Search')], max_length=20)),
                ('value', models.FloatField(blank=True, help_text='Rating value, purchase amount, etc.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, help_text='Where the event came from', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recommendations.itemcatalog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recommendations.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('similar_items', 'Similar Items'), ('also_bought', 'Users Also Bought'), ('trending', 'Trending'), ('personalized', 'Personalized For You'), ('category', 'Category Recommendations'), ('search', 'Search-Based')], max_length=30)),
                ('recommended_items', models.JSONField(default=list)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('experiment_id', models.CharField(blank=True, max_length=100)),
                ('variant', models.CharField(blank=True, max_length=50)),
                ('items_clicked', models.JSONField(default=list)),
                ('items_purchased', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_requests', to='recommendations.itemcatalog')),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.recommendationmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_requests', to='recommendations.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='itemcatalog',
            index=models.Index(fields=['tenant', 'item_type', 'is_active'], name='recommendat_tenant__8c01db_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalog',
            index=models.Index(fields=['tenant', 'category'], name='recommendat_tenant__36f5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='itemcatalog',
            index=models.Index(fields=['purchase_count'], name='recommendat_purchas_9dbe0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcatalog',
            unique_together={('tenant', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['tenant', 'external_user_id'], name='recommendat_tenant__049884_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('tenant', 'external_user_id')},
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['tenant', 'user', 'event_type'], name='recommendat_tenant__c04124_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['tenant', 'item', 'event_type'], name='recommendat_tenant__a5f073_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['tenant', 'timestamp'], name='recommendat_tenant__939484_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrequest',
            index=models.Index(fields=['tenant', 'strategy', 'timestamp'], name='recommendat_tenant__df7f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationrequest',
            index=models.Index(fields=['experiment_id'], name='recommendat_experim_1846c2_idx'),
        ),
    ]
