# Generated by Django 5.0 on 2025-11-27 20:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mailchimp_enabled', models.BooleanField(default=False)),
                ('mailchimp_api_key', models.CharField(blank=True, max_length=100)),
                ('mailchimp_server_prefix', models.CharField(blank=True, max_length=10)),
                ('sendgrid_enabled', models.BooleanField(default=False)),
                ('sendgrid_api_key', models.CharField(blank=True, max_length=100)),
                ('convertkit_enabled', models.BooleanField(default=False)),
                ('convertkit_api_key', models.CharField(blank=True, max_length=100)),
                ('convertkit_api_secret', models.CharField(blank=True, max_length=100)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('default_from_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('double_optin', models.BooleanField(default=True, help_text='Require email confirmation')),
                ('welcome_email_enabled', models.BooleanField(default=True)),
                ('welcome_email_subject', models.CharField(default='Welcome!', max_length=200)),
                ('welcome_email_body', models.TextField(blank=True)),
                ('mailchimp_list_id', models.CharField(blank=True, max_length=50)),
                ('sendgrid_list_id', models.CharField(blank=True, max_length=50)),
                ('convertkit_form_id', models.CharField(blank=True, max_length=50)),
                ('subscriber_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_lists', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='pending', max_length=20)),
                ('confirmation_token', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(max_length=100, unique=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_reason', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='email_lists.emaillist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_list', 'status'], name='email_lists_email_l_18d885_idx'), models.Index(fields=['email_list', 'email'], name='email_lists_email_l_b7edb3_idx'), models.Index(fields=['unsubscribe_token'], name='email_lists_unsubsc_3bee60_idx'), models.Index(fields=['confirmation_token'], name='email_lists_confirm_79415c_idx')],
                'unique_together': {('email_list', 'email')},
            },
        ),
    ]
