# Generated by Django 5.0 on 2025-11-27 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_id', models.CharField(blank=True, max_length=255)),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('app', 'Application'), ('system', 'System')], default='user', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.folder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_folders', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tenant', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('r2', 'Cloudflare R2'), ('gcs', 'Google Cloud Storage')], default='local', max_length=20)),
                ('bucket_name', models.CharField(blank=True, max_length=100)),
                ('access_key', models.CharField(blank=True, max_length=200)),
                ('secret_key', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('endpoint_url', models.URLField(blank=True)),
                ('cdn_url', models.URLField(blank=True)),
                ('max_file_size_mb', models.PositiveIntegerField(default=50)),
                ('max_storage_gb', models.PositiveIntegerField(default=10)),
                ('allowed_image_types', models.JSONField(blank=True, default=list, help_text="e.g., ['jpg', 'png', 'gif', 'webp']")),
                ('allowed_file_types', models.JSONField(blank=True, default=list, help_text="e.g., ['pdf', 'doc', 'docx', 'xlsx']")),
                ('auto_optimize_images', models.BooleanField(default=True)),
                ('max_image_dimension', models.PositiveIntegerField(default=2048)),
                ('jpeg_quality', models.PositiveIntegerField(default=85)),
                ('generate_thumbnails', models.BooleanField(default=True)),
                ('thumbnail_sizes', models.JSONField(blank=True, default=list, help_text='e.g., [150, 300, 600]')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('image_size_bytes', models.BigIntegerField(default=0)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('document_size_bytes', models.BigIntegerField(default=0)),
                ('other_count', models.PositiveIntegerField(default=0)),
                ('other_size_bytes', models.BigIntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_usage', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=500)),
                ('stored_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_url', models.URLField(blank=True, max_length=2000)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('file_extension', models.CharField(max_length=20)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('is_image', models.BooleanField(default=False)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnails', models.JSONField(blank=True, default=dict)),
                ('owner_id', models.CharField(blank=True, max_length=255)),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('app', 'Application'), ('system', 'System')], default='user', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_files', to='tenants.tenant')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='storage.folder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'folder', 'is_deleted'], name='storage_fil_tenant__c1656e_idx'), models.Index(fields=['tenant', 'owner_id', 'is_deleted'], name='storage_fil_tenant__c61672_idx'), models.Index(fields=['tenant', 'content_type'], name='storage_fil_tenant__d899c1_idx')],
            },
        ),
    ]
