# Generated by Django 5.0 on 2025-12-18 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_unique_together_project_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDesignRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Rules', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Only one can be active')),
                ('font_rules', models.TextField(default="TYPOGRAPHY RULES:\n- Primary font: Apple San Francisco (-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'SF Pro Text', system-ui, sans-serif)\n- NEVER use any other font unless explicitly requested\n- Headings: Bold, proper hierarchy (h1 > h2 > h3)\n- Body text: 16-18px, line-height 1.6\n- Never use font sizes below 14px")),
                ('color_rules', models.TextField(default='COLOR RULES:\n- Use modern, professional color palettes\n- Primary colors should have good contrast\n- Always ensure text is readable (WCAG AA minimum)\n- Dark mode: Use #0a0a0a or #111111 backgrounds, not pure black\n- Gradients: Subtle, professional (not rainbow)\n- Accent colors: Use sparingly for CTAs and highlights')),
                ('layout_rules', models.TextField(default='LAYOUT RULES:\n- Mobile-first responsive design\n- Max content width: 1200px centered\n- Consistent padding: 20px mobile, 40px tablet, 60px desktop\n- Use CSS Grid or Flexbox, never tables for layout\n- Proper spacing between sections (60-100px)\n- Hero sections: Full viewport height or at least 600px')),
                ('component_rules', models.TextField(default='COMPONENT RULES:\n- Buttons: Rounded corners (8-12px), clear hover states\n- Cards: Subtle shadows, rounded corners\n- Forms: Clear labels, visible focus states\n- Images: Always have alt text, use object-fit: cover\n- Icons: Consistent size and style throughout')),
                ('forbidden_patterns', models.TextField(default='NEVER DO THESE:\n- No Lorem Ipsum or placeholder text\n- No broken image links or placeholder.jpg\n- No inline styles mixing with CSS classes\n- No !important unless absolutely necessary\n- No fixed pixel widths that break mobile\n- No auto-playing videos or audio\n- No popup modals on page load\n- No Comic Sans, Papyrus, or novelty fonts\n- No rainbow gradients or neon colors (unless explicitly requested)\n- No stock photo watermarks')),
                ('quality_standards', models.TextField(default='QUALITY STANDARDS:\n- All components must be self-contained\n- Code must be clean and readable\n- No console.log statements in production code\n- Proper error handling for any data operations\n- Accessible: proper ARIA labels, keyboard navigation\n- Performance: No unnecessary re-renders')),
                ('custom_rules', models.TextField(blank=True, help_text='Any additional rules specific to your brand/style')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Design Rules',
                'verbose_name_plural': 'Admin Design Rules',
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('constraint_type', models.CharField(choices=[('style', 'Styling Rule'), ('layout', 'Layout Rule'), ('content', 'Content Rule'), ('forbidden', 'Forbidden Pattern'), ('required', 'Required Pattern')], default='style', max_length=30)),
                ('rule_text', models.TextField(default='', help_text='The actual constraint text to inject into prompts')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority constraints are applied first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_key', models.CharField(help_text="Internal key like 'library_search', 'code_generation', etc.", max_length=100, unique=True)),
                ('customer_message', models.CharField(help_text='Friendly message shown to customer', max_length=200)),
                ('message_variants', models.JSONField(blank=True, default=list, help_text='Alternative messages (list of strings, picked randomly)')),
                ('min_display_seconds', models.IntegerField(default=2, help_text='Minimum time to show this message')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['operation_key'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(db_index=True)),
                ('query_hash', models.CharField(max_length=64, unique=True)),
                ('result', models.JSONField(default=dict)),
                ('source', models.CharField(default='ai', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='code_library.librarycategory')),
            ],
            options={
                'verbose_name_plural': 'Library Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(help_text='What this component does')),
                ('item_type', models.CharField(choices=[('component', 'React Component'), ('section', 'Page Section'), ('page', 'Full Page'), ('template', 'Complete Template'), ('utility', 'Utility/Helper')], default='component', max_length=20)),
                ('code', models.TextField(help_text='The React component code')),
                ('language', models.CharField(default='tsx', max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for matching (salon, hair, pricing, hero...)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization (list of strings)')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search (list of floats)', null=True)),
                ('quality_score', models.FloatField(default=0.5, help_text='0-1 score, higher is better. Set by admin.')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Available for use')),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by admin')),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='ai', help_text='ai or admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_library.librarycategory')),
                ('source_project', models.ForeignKey(blank=True, help_text='Project this was first created for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['-quality_score', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItemUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_type', models.CharField(choices=[('full', 'Used as-is'), ('adapted', 'Adapted'), ('inspired', 'Inspired by')], default='adapted', max_length=20)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='code_library.libraryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_usages', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(default='1.0.0', max_length=20)),
                ('code', models.TextField()),
                ('changelog', models.TextField(blank=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='code_library.libraryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['item_type', 'is_active'], name='code_librar_item_ty_8c9007_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['quality_score'], name='code_librar_quality_4be5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['usage_count'], name='code_librar_usage_c_f54914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryversion',
            unique_together={('item', 'version_number')},
        ),
    ]
