# Generated by Django 5.0 on 2025-11-27 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_unique_together_project_tenant_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('query_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('research_type', models.CharField(choices=[('web', 'Web Search'), ('github', 'GitHub'), ('npm', 'NPM'), ('pypi', 'PyPI'), ('docs', 'Documentation')], max_length=20)),
                ('results', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('result_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Research Cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='📁', max_length=50)),
                ('color', models.CharField(blank=True, default='#3B82F6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='code_library.librarycategory')),
            ],
            options={
                'verbose_name_plural': 'Library Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('item_type', models.CharField(choices=[('component', 'Component'), ('service', 'Service'), ('utility', 'Utility'), ('template', 'Template'), ('hook', 'React Hook'), ('api', 'API Endpoint'), ('model', 'Data Model'), ('style', 'Style/CSS'), ('config', 'Configuration'), ('snippet', 'Code Snippet')], max_length=20)),
                ('language', models.CharField(choices=[('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('yaml', 'YAML'), ('markdown', 'Markdown'), ('sql', 'SQL'), ('shell', 'Shell')], max_length=20)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('usage_example', models.TextField(blank=True)),
                ('documentation', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True)),
                ('embedding_model', models.CharField(blank=True, default='text-embedding-3-small', max_length=100)),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of npm/pip packages required')),
                ('quality_score', models.FloatField(default=0.0, help_text='0-100 quality score')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('generated', 'AI Generated'), ('imported', 'Imported'), ('manual', 'Manually Added'), ('curated', 'Curated/Official')], default='generated', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Available to all tenants')),
                ('is_deprecated', models.BooleanField(default=False)),
                ('deprecation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='code_library.librarycategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_library_items', to=settings.AUTH_USER_MODEL)),
                ('requires', models.ManyToManyField(blank=True, help_text='Other library items this depends on', related_name='required_by', to='code_library.libraryitem')),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for global/shared items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-quality_score', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LibraryItemUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('usage_type', models.CharField(choices=[('direct', 'Direct Copy'), ('modified', 'Modified'), ('referenced', 'Referenced')], max_length=20)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='code_library.libraryitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_usages', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='Semantic version (e.g., 1.0.0)', max_length=20)),
                ('code', models.TextField()),
                ('changelog', models.TextField(blank=True)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='code_library.libraryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('constraint_type', models.CharField(choices=[('security', 'Security'), ('styling', 'Styling'), ('architecture', 'Architecture'), ('api', 'API Usage'), ('database', 'Database'), ('react', 'React Patterns'), ('python', 'Python Patterns'), ('custom', 'Custom')], max_length=20)),
                ('content', models.TextField(help_text='Markdown content of the constraint')),
                ('rules', models.JSONField(blank=True, default=list, help_text='Parsed list of rules')),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Languages/item types this applies to')),
                ('priority', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for global constraints', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-priority', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['tenant', 'item_type'], name='code_librar_tenant__b60e21_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['language', 'item_type'], name='code_librar_languag_b3ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['is_active', 'is_public'], name='code_librar_is_acti_407612_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['quality_score'], name='code_librar_quality_4be5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='libraryitem',
            index=models.Index(fields=['usage_count'], name='code_librar_usage_c_f54914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryitem',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='libraryversion',
            unique_together={('item', 'version')},
        ),
    ]
