# Generated by Django 5.0 on 2025-12-18 04:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_library', '0002_seed_default_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=100)),
                ('decision', models.CharField(choices=[('reused', 'Reused from library'), ('generated', 'Generated new'), ('gray_zone', 'Gray zone - manual review')], db_index=True, max_length=20)),
                ('match_score', models.FloatField(default=0)),
                ('library_item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('candidate_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision', 'created_at'], name='code_librar_decisio_a80132_idx')],
            },
        ),
    ]
