# Generated by Django 5.0 on 2025-12-18 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_library', '0003_add_reuse_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='needs_review',
            field=models.BooleanField(default=True, help_text='Flagged for admin review'),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Auto-approved, admin reviews after'),
        ),
        migrations.CreateModel(
            name='AdminFeedbackQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='Question for admin in plain English')),
                ('context', models.TextField(blank=True, help_text='What prompted this question')),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('quality', 'Rate quality (1-5)'), ('like_dislike', 'Like or dislike specific aspect'), ('improvement', 'Suggest improvement'), ('categorization', 'Confirm categorization')], default='quality', max_length=20)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_questions', to='code_library.libraryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
