# Generated by Django 5.0 on 2025-12-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_library', '0005_add_connector_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRecord',
            fields=[
                ('problem_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('problem_class', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('occurrences', models.IntegerField(default=1)),
                ('systemic_fix_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fix_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='deprecation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='documentation',
            field=models.TextField(blank=True, default='', help_text='Documentation for component'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='source',
            field=models.CharField(blank=True, default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='usage_example',
            field=models.TextField(blank=True, default='', help_text='Example usage code'),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords for matching (list of strings)'),
        ),
    ]
