# Generated by Django 5.0 on 2026-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_library', '0007_fix_missing_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructionSolutionRecord',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('instruction_text', models.TextField()),
                ('missing_enforcement', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending - needs enforcement'), ('fixed', 'Fixed - enforcement added'), ('acknowledged', 'Acknowledged - intentional')], db_index=True, default='pending', max_length=20)),
                ('fixed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='language',
            field=models.CharField(default='jsx', max_length=20),
        ),
    ]
