# Generated by Django 5.0 on 2025-11-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard'), ('crud', 'CRUD Application'), ('blog', 'Blog/CMS'), ('ecommerce', 'E-commerce'), ('social', 'Social Network'), ('tool', 'Utility Tool')], max_length=20)),
                ('schema_template', models.JSONField(help_text='Database schema template')),
                ('api_template', models.JSONField(help_text='API endpoints template')),
                ('ui_template', models.JSONField(help_text='UI components template')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
