# Generated by Django 5.0 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('internal_ops', 'Internal Ops Dashboards'), ('client_portal', 'Client Portals'), ('admin_panel', 'Admin Panels'), ('ecommerce', 'E-commerce')], max_length=20),
        ),
    ]
