# Generated by Django 5.0 on 2025-11-27 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('dashboard', 'Dashboard'), ('ecommerce', 'E-Commerce'), ('crm', 'CRM'), ('cms', 'Content Management'), ('analytics', 'Analytics'), ('project', 'Project Management'), ('hr', 'HR Management'), ('finance', 'Finance'), ('support', 'Support/Helpdesk'), ('social', 'Social Media'), ('other', 'Other')], max_length=30)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('pages', models.JSONField(default=list)),
                ('data_sources', models.JSONField(default=list)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdminBuilderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(default='Admin Panel', max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', max_length=7)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('allow_custom_css', models.BooleanField(default=True)),
                ('allow_custom_js', models.BooleanField(default=False)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_head_html', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_builder_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('api', 'External API'), ('database', 'Database Collection'), ('static', 'Static Data'), ('checkout_orders', 'Checkout Orders'), ('checkout_products', 'Checkout Products'), ('cabinet_users', 'Cabinet Users'), ('cabinet_tickets', 'Support Tickets'), ('storage_files', 'Storage Files'), ('analytics_events', 'Analytics Events'), ('custom', 'Custom Query')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('cache_enabled', models.BooleanField(default=True)),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=300)),
                ('transform', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('page_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('list', 'List View'), ('form', 'Form'), ('detail', 'Detail View'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('show_in_nav', models.BooleanField(default=True)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('requires_auth', models.BooleanField(default=True)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_builder.adminpage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_pages', to='tenants.tenant')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='admin_builder.datasource')),
            ],
            options={
                'ordering': ['nav_order', 'name'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ExportedAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('code', models.JSONField(default=dict)),
                ('framework', models.CharField(default='react', max_length=20)),
                ('build_status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('build_log', models.TextField(blank=True)),
                ('download_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_admins', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart_bar', 'Bar Chart'), ('chart_line', 'Line Chart'), ('chart_pie', 'Pie Chart'), ('chart_area', 'Area Chart'), ('stat_card', 'Stat Card'), ('table', 'Data Table'), ('form', 'Form'), ('text', 'Text/HTML'), ('image', 'Image'), ('button', 'Button'), ('card', 'Card'), ('list', 'List'), ('calendar', 'Calendar'), ('map', 'Map'), ('video', 'Video'), ('iframe', 'IFrame'), ('divider', 'Divider'), ('spacer', 'Spacer'), ('tabs', 'Tabs'), ('accordion', 'Accordion'), ('modal', 'Modal Trigger'), ('custom', 'Custom Component')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('data_query', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('visibility_conditions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='admin_builder.datasource')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='admin_builder.adminpage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
