# Generated by Django 5.0 on 2026-01-26 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_services', '0001_initial'),
        ('projects', '0006_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('review_component', 'Review Component'), ('fix_bug', 'Fix Bug'), ('improve_quality', 'Improve Quality'), ('update_keywords', 'Update Keywords'), ('check_compatibility', 'Check Compatibility')], max_length=50)),
                ('component_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Improvement Task',
                'verbose_name_plural': 'Improvement Tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens', models.JSONField(default=dict, help_text='CSS variable overrides')),
                ('custom_css', models.TextField(blank=True, help_text='Additional custom CSS')),
                ('primary_font', models.CharField(blank=True, max_length=100)),
                ('heading_font', models.CharField(blank=True, max_length=100)),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Design',
                'verbose_name_plural': 'Project Designs',
            },
        ),
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('general', 'General'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('quality', 'Quality Issue')], default='general', max_length=50)),
                ('rating', models.IntegerField(default=3)),
                ('message', models.TextField()),
                ('component_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Feedback',
                'verbose_name_plural': 'Project Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='project_ser_project_b8832a_idx',
            old_name='project_ser_project_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='project_ser_project_8950c8_idx',
            old_name='project_ser_project_def456_idx',
        ),
        migrations.AddField(
            model_name='projectdesign',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='projects.project'),
        ),
    ]
