# Generated by Django 5.0 on 2025-11-27 22:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_unique_together_project_tenant_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_visitors', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('emails_collected', models.IntegerField(default=0)),
                ('email_changes', models.IntegerField(default=0)),
                ('magic_links_sent', models.IntegerField(default=0)),
                ('magic_links_clicked', models.IntegerField(default=0)),
                ('accounts_created', models.IntegerField(default=0)),
                ('projects_created', models.IntegerField(default=0)),
                ('request_to_email_rate', models.FloatField(blank=True, null=True)),
                ('email_to_click_rate', models.FloatField(blank=True, null=True)),
                ('click_to_account_rate', models.FloatField(blank=True, null=True)),
                ('overall_conversion_rate', models.FloatField(blank=True, null=True)),
                ('total_llm_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('issues_flagged', models.IntegerField(default=0)),
                ('issues_fixed', models.IntegerField(default=0)),
                ('at_risk_customers', models.IntegerField(default=0)),
                ('healthy_customers', models.IntegerField(default=0)),
                ('ad_impressions', models.IntegerField(default=0)),
                ('ad_clicks', models.IntegerField(default=0)),
                ('ad_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ad_conversions', models.IntegerField(default=0)),
                ('ad_ctr', models.FloatField(blank=True, null=True)),
                ('ad_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ad_cpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('conversions_by_source', models.JSONField(default=dict)),
                ('conversions_by_campaign', models.JSONField(default=dict)),
                ('top_requests', models.JSONField(default=list)),
                ('common_issues', models.JSONField(default=list)),
                ('all_sessions', models.JSONField(default=list)),
                ('report_sent', models.BooleanField(default=False)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('daily_report', 'Daily Report'), ('alert', 'Alert'), ('at_risk_customer', 'At-Risk Customer'), ('high_volume', 'High Volume'), ('quality_issue', 'Quality Issue')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.dailyreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('initial_request', models.TextField(help_text='What the user typed in the main input')),
                ('status', models.CharField(choices=[('request_submitted', 'Request Submitted'), ('email_requested', 'Email Requested'), ('email_provided', 'Email Provided'), ('email_changed', 'Email Changed'), ('magic_link_sent', 'Magic Link Sent'), ('magic_link_clicked', 'Magic Link Clicked'), ('account_created', 'Account Created'), ('project_created', 'Project Created'), ('building', 'Building'), ('deployed', 'Deployed'), ('abandoned', 'Abandoned')], default='request_submitted', max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('magic_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('magic_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('magic_link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('magic_link_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('email_change_count', models.IntegerField(default=0)),
                ('previous_emails', models.JSONField(default=list)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('referrer', models.URLField(blank=True)),
                ('landing_page', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('converted_to_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('converted_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('request_submitted', 'Request Submitted'), ('email_form_shown', 'Email Form Shown'), ('email_entered', 'Email Entered'), ('email_changed', 'Email Changed'), ('magic_link_sent', 'Magic Link Sent'), ('magic_link_resent', 'Magic Link Resent'), ('magic_link_clicked', 'Magic Link Clicked'), ('magic_link_expired', 'Magic Link Expired'), ('account_created', 'Account Created'), ('project_created', 'Project Created'), ('build_started', 'Build Started'), ('build_progress', 'Build Progress'), ('build_completed', 'Build Completed'), ('deploy_started', 'Deploy Started'), ('deploy_completed', 'Deploy Completed'), ('error', 'Error'), ('session_timeout', 'Session Timeout')], max_length=30)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('old_email', models.EmailField(blank=True, max_length=254)),
                ('new_email', models.EmailField(blank=True, max_length=254)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='onboarding.landingsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='landingsession',
            index=models.Index(fields=['status', 'created_at'], name='onboarding__status_9ec846_idx'),
        ),
        migrations.AddIndex(
            model_name='landingsession',
            index=models.Index(fields=['email', 'created_at'], name='onboarding__email_a56a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='landingsession',
            index=models.Index(fields=['utm_source', 'utm_campaign'], name='onboarding__utm_sou_4b9698_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['session', 'event_type'], name='onboarding__session_f8539f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='onboarding__event_t_1d38f8_idx'),
        ),
    ]
