# Generated by Django 5.0 on 2025-11-27 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsession',
            name='active_time_seconds',
            field=models.IntegerField(default=0, help_text='Time actively engaged (not idle)'),
        ),
        migrations.AddField(
            model_name='landingsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingsession',
            name='total_characters_typed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landingsession',
            name='total_inputs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landingsession',
            name='total_time_seconds',
            field=models.IntegerField(default=0, help_text='Total time spent in session (seconds)'),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='user_input',
            field=models.TextField(blank=True, help_text='What the user typed/entered'),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('request_submitted', 'Request Submitted'), ('request_modified', 'Request Modified'), ('input_typed', 'Input Typed'), ('email_form_shown', 'Email Form Shown'), ('email_entered', 'Email Entered'), ('email_changed', 'Email Changed'), ('magic_link_sent', 'Magic Link Sent'), ('magic_link_resent', 'Magic Link Resent'), ('magic_link_clicked', 'Magic Link Clicked'), ('magic_link_expired', 'Magic Link Expired'), ('account_created', 'Account Created'), ('project_created', 'Project Created'), ('build_started', 'Build Started'), ('build_progress', 'Build Progress'), ('build_completed', 'Build Completed'), ('deploy_started', 'Deploy Started'), ('deploy_completed', 'Deploy Completed'), ('chat_message', 'Chat Message'), ('feature_request', 'Feature Request'), ('error', 'Error'), ('session_timeout', 'Session Timeout'), ('page_leave', 'Page Leave'), ('page_return', 'Page Return')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('initial_request', 'Initial Request (Landing)'), ('request_edit', 'Request Edit'), ('follow_up', 'Follow-up Message'), ('feature_add', 'Feature Addition'), ('code_request', 'Code Generation Request'), ('code_edit', 'Code Edit Request'), ('chat_message', 'Chat Message'), ('feedback', 'Feedback'), ('bug_report', 'Bug Report'), ('other', 'Other')], max_length=30)),
                ('input_text', models.TextField(help_text='Exactly what the user typed')),
                ('context', models.TextField(blank=True, help_text='What was on screen when they typed this')),
                ('ai_response', models.TextField(blank=True)),
                ('time_to_type_seconds', models.IntegerField(blank=True, help_text='How long they spent typing this', null=True)),
                ('was_successful', models.BooleanField(blank=True, null=True)),
                ('user_satisfaction', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_input', models.ForeignKey(blank=True, help_text='The input this was a follow-up to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.userinput')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inputs', to='onboarding.landingsession')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_inputs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['input_type', 'timestamp'], name='onboarding__input_t_31bacd_idx'), models.Index(fields=['session', 'timestamp'], name='onboarding__session_fe9776_idx'), models.Index(fields=['user', 'timestamp'], name='onboarding__user_id_39f189_idx')],
            },
        ),
    ]
