# Generated by Django 5.0 on 2026-01-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_add_input_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsession',
            name='mode',
            field=models.CharField(choices=[('discussion', 'Discussion/Planning'), ('building', 'Building')], default='building', max_length=20),
        ),
        migrations.AddField(
            model_name='landingsession',
            name='requirements_checklist',
            field=models.TextField(blank=True, help_text='Structured planning outputs/checklist from discussion mode', null=True),
        ),
    ]
