# Generated by Django 5.0 on 2026-01-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelabelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', max_length=7)),
                ('accent_color', models.CharField(default='#10b981', max_length=7)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('domain_verified', models.BooleanField(default=False)),
                ('footer_text', models.CharField(blank=True, max_length=255)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whitelabel', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Whitelabel Configuration',
                'verbose_name_plural': 'Whitelabel Configurations',
            },
        ),
    ]
