# Generated by Django 5.0 on 2026-01-15 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_whitelabelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('sso_type', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect')], default='saml', max_length=10)),
                ('idp_entity_id', models.CharField(blank=True, max_length=255)),
                ('idp_sso_url', models.URLField(blank=True)),
                ('idp_certificate', models.TextField(blank=True)),
                ('oidc_issuer', models.URLField(blank=True)),
                ('oidc_client_id', models.CharField(blank=True, max_length=255)),
                ('oidc_client_secret', models.CharField(blank=True, max_length=255)),
                ('domain_restriction', models.CharField(blank=True, max_length=255)),
                ('auto_provision_users', models.BooleanField(default=True)),
                ('default_role', models.CharField(default='member', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SSO Configuration',
                'verbose_name_plural': 'SSO Configurations',
            },
        ),
    ]
