# Generated by Django 5.0 on 2025-11-27 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (system)')], default='light', max_length=20)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('welcome_message', models.TextField(default='👋 Hi! How can I help you today?')),
                ('placeholder_text', models.CharField(default='Type your message...', max_length=200)),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google (Gemini)'), ('grok', 'xAI (Grok)')], default='openai', max_length=20)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('system_prompt', models.TextField(default='You are a helpful customer support assistant. Be friendly, concise, and helpful.')),
                ('knowledge_base', models.TextField(blank=True, help_text='Additional context for the AI (product info, FAQs, etc.)')),
                ('collect_email', models.BooleanField(default=False)),
                ('show_powered_by', models.BooleanField(default=True)),
                ('enable_file_upload', models.BooleanField(default=False)),
                ('max_messages_per_session', models.PositiveIntegerField(default=50)),
                ('max_sessions_per_day', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_widgets', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('page_url', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('escalated', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.chatwidget')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_own_keys', models.BooleanField(default=False)),
                ('openai_api_key', models.CharField(blank=True, max_length=200)),
                ('anthropic_api_key', models.CharField(blank=True, max_length=200)),
                ('gemini_api_key', models.CharField(blank=True, max_length=200)),
                ('grok_api_key', models.CharField(blank=True, max_length=200)),
                ('default_provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4o)'), ('anthropic', 'Anthropic (Claude)'), ('gemini', 'Google (Gemini)'), ('grok', 'xAI (Grok)')], default='openai', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='chat_chatme_session_70d41b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['widget', 'visitor_id'], name='chat_chatse_widget__d798ba_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['widget', 'started_at'], name='chat_chatse_widget__8d7376_idx'),
        ),
    ]
