# Generated by Django 5.0 on 2025-11-27 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Competitor name', max_length=200)),
                ('domain', models.CharField(help_text='Domain to track (e.g., competitor.com)', max_length=255)),
                ('website_url', models.URLField(help_text='Full URL of competitor website')),
                ('track_homepage', models.BooleanField(default=True)),
                ('track_blog', models.BooleanField(default=True)),
                ('track_pricing', models.BooleanField(default=True)),
                ('track_features', models.BooleanField(default=True)),
                ('custom_pages', models.JSONField(blank=True, default=list, help_text='List of custom page URLs to track')),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_type', models.CharField(choices=[('homepage', 'Homepage'), ('blog', 'Blog'), ('pricing', 'Pricing'), ('features', 'Features'), ('custom', 'Custom Page')], max_length=20)),
                ('page_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('headings', models.JSONField(blank=True, default=list, help_text='List of h1-h6 headings')),
                ('content_text', models.TextField(blank=True, help_text='Extracted text content')),
                ('content_hash', models.CharField(help_text='SHA256 hash for change detection', max_length=64)),
                ('features_mentioned', models.JSONField(blank=True, default=list)),
                ('pricing_info', models.JSONField(blank=True, default=dict)),
                ('blog_posts', models.JSONField(blank=True, default=list)),
                ('http_status', models.IntegerField(default=200)),
                ('screenshot_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='marketing.competitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('new_feature', 'New Feature'), ('pricing_change', 'Pricing Change'), ('new_blog_post', 'New Blog Post'), ('content_update', 'Content Update'), ('new_page', 'New Page'), ('layout_change', 'Layout Change')], max_length=30)),
                ('page_type', models.CharField(choices=[('homepage', 'Homepage'), ('blog', 'Blog'), ('pricing', 'Pricing'), ('features', 'Features'), ('custom', 'Custom Page')], max_length=20)),
                ('page_url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('importance_score', models.IntegerField(default=5, help_text='1-10 importance score from AI')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='marketing.competitor')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_competitor_changes', to=settings.AUTH_USER_MODEL)),
                ('new_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_as_new', to='marketing.competitorsnapshot')),
                ('old_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_as_old', to='marketing.competitorsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('your_domain', models.CharField(help_text='Your domain to track ranking for', max_length=255)),
                ('track_competitors', models.BooleanField(default=True, help_text='Also track competitor rankings for this keyword')),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='tenants.tenant')),
            ],
            options={
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='KeywordRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='Domain this ranking is for', max_length=255)),
                ('position', models.IntegerField(blank=True, help_text='Position in search results (null if not in top 100)', null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('snippet', models.TextField(blank=True)),
                ('search_engine', models.CharField(default='google', max_length=50)),
                ('search_location', models.CharField(default='us', max_length=100)),
                ('previous_position', models.IntegerField(blank=True, null=True)),
                ('position_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='marketing.keyword')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('report_email', models.EmailField(blank=True, help_text='Email to receive reports (defaults to tenant owner email)', max_length=254)),
                ('report_enabled', models.BooleanField(default=True)),
                ('additional_recipients', models.JSONField(blank=True, default=list, help_text='List of additional email addresses')),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
                ('next_report_at', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Marketing Configuration',
                'verbose_name_plural': 'Marketing Configurations',
            },
        ),
        migrations.CreateModel(
            name='MarketingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('scheduled', 'Scheduled Report'), ('manual', 'Manual Report'), ('alert', 'Alert Report')], default='scheduled', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('competitor_analysis', models.JSONField(blank=True, default=dict)),
                ('keyword_rankings', models.JSONField(blank=True, default=dict)),
                ('changes_detected', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('ai_executive_summary', models.TextField(blank=True)),
                ('ai_key_insights', models.JSONField(blank=True, default=list)),
                ('ai_action_items', models.JSONField(blank=True, default=list)),
                ('html_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('sent_to', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('include_competitor_analysis', models.BooleanField(default=True)),
                ('include_keyword_rankings', models.BooleanField(default=True)),
                ('include_changes', models.BooleanField(default=True)),
                ('include_recommendations', models.BooleanField(default=True)),
                ('include_ai_insights', models.BooleanField(default=True)),
                ('html_template', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for system templates', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['tenant', 'is_active'], name='marketing_c_tenant__55739f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='competitor',
            unique_together={('tenant', 'domain')},
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['competitor', 'page_type', '-created_at'], name='marketing_c_competi_657d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorsnapshot',
            index=models.Index(fields=['content_hash'], name='marketing_c_content_ff9004_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorchange',
            index=models.Index(fields=['competitor', '-created_at'], name='marketing_c_competi_eb0b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorchange',
            index=models.Index(fields=['change_type', '-created_at'], name='marketing_c_change__58e489_idx'),
        ),
        migrations.AddIndex(
            model_name='competitorchange',
            index=models.Index(fields=['importance_score'], name='marketing_c_importa_5205e8_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['tenant', 'is_active'], name='marketing_k_tenant__24c5ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('tenant', 'keyword', 'your_domain')},
        ),
        migrations.AddIndex(
            model_name='keywordranking',
            index=models.Index(fields=['keyword', '-created_at'], name='marketing_k_keyword_14df04_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordranking',
            index=models.Index(fields=['domain', '-created_at'], name='marketing_k_domain_3c6ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingreport',
            index=models.Index(fields=['tenant', '-created_at'], name='marketing_m_tenant__f1a847_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingreport',
            index=models.Index(fields=['status', '-created_at'], name='marketing_m_status_18aa2a_idx'),
        ),
    ]
