# Generated by Django 5.0 on 2025-11-27 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_project_unique_together_project_tenant_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('monthly_credits', models.IntegerField(default=0, help_text='Credits included per month')),
                ('monthly_tokens', models.IntegerField(default=0, help_text='Token limit per month (0 = based on credits)')),
                ('credit_overage_price', models.DecimalField(decimal_places=4, default=0.1, help_text='Price per additional credit', max_digits=6)),
                ('max_projects', models.IntegerField(default=1)),
                ('max_team_members', models.IntegerField(default=1)),
                ('max_storage_gb', models.IntegerField(default=1)),
                ('max_api_calls_daily', models.IntegerField(default=100)),
                ('features', models.JSONField(blank=True, default=list)),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=100)),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('generate', 'Code Generation'), ('modify', 'Code Modification'), ('chat', 'AI Chat'), ('analyze', 'Code Analysis'), ('explain', 'Code Explanation'), ('debug', 'Debugging'), ('other', 'Other')], max_length=20)),
                ('model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('claude-3-opus', 'Claude 3 Opus'), ('claude-3-sonnet', 'Claude 3 Sonnet'), ('claude-3-haiku', 'Claude 3 Haiku'), ('gemini-pro', 'Gemini Pro'), ('gemini-ultra', 'Gemini Ultra')], max_length=50)),
                ('prompt', models.TextField(help_text="User's request/prompt")),
                ('system_prompt', models.TextField(blank=True)),
                ('response', models.TextField(help_text="LLM's response")),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('credits_charged', models.IntegerField(default=1)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('was_modified', models.BooleanField(blank=True, null=True)),
                ('was_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_requests', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('subscription', 'Monthly Subscription'), ('purchase', 'Credit Purchase'), ('usage', 'Credit Usage'), ('refund', 'Refund'), ('bonus', 'Bonus Credits'), ('adjustment', 'Admin Adjustment')], max_length=20)),
                ('credits', models.IntegerField()),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='tenants.tenant')),
                ('llm_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credits.llmrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits_remaining', models.IntegerField(default=0, help_text='Credits left this period')),
                ('credits_used_this_period', models.IntegerField(default=0)),
                ('tokens_used_this_period', models.IntegerField(default=0)),
                ('purchased_credits', models.IntegerField(default=0, help_text='Extra purchased credits')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_credits_used', models.IntegerField(default=0)),
                ('total_tokens_generated', models.IntegerField(default=0)),
                ('total_requests', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to='tenants.tenant')),
                ('subscription_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credits.subscriptiontier')),
            ],
        ),
        migrations.CreateModel(
            name='UsageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_requests', models.IntegerField(default=0)),
                ('total_credits_used', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('usage_by_model', models.JSONField(blank=True, default=dict)),
                ('usage_by_type', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('acceptance_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddIndex(
            model_name='llmrequest',
            index=models.Index(fields=['tenant', 'created_at'], name='credits_llm_tenant__7eaa60_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrequest',
            index=models.Index(fields=['model', 'created_at'], name='credits_llm_model_119a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrequest',
            index=models.Index(fields=['request_type', 'created_at'], name='credits_llm_request_696238_idx'),
        ),
        migrations.AddIndex(
            model_name='llmrequest',
            index=models.Index(fields=['user_rating'], name='credits_llm_user_ra_a4f6d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagereport',
            unique_together={('tenant', 'period_type', 'period_start')},
        ),
    ]
