# Generated by Django 5.0 on 2025-12-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmrequest',
            name='model',
            field=models.CharField(choices=[('claude-opus-4.5', 'Claude Opus 4.5'), ('claude-sonnet-4', 'Claude Sonnet 4'), ('claude-haiku-3.5', 'Claude Haiku 3.5'), ('text-embedding-3-small', 'OpenAI Embeddings'), ('gpt-4', 'GPT-4'), ('claude-3-opus', 'Claude 3 Opus')], max_length=50),
        ),
    ]
